### ISSUE TITLE
Not clear how to add a new lane

### ISSUE THREAD

**Issue by prateekchachra** [lourenci/react-kanban#164]
Can you please make it clear how to add the new lane by default? I'm having trouble trying to figure it out.

**Comment by prateekchachra** [comment]
Figured it out. Please mention in the docs that adding the listeners is compoulsory for these to work.

**Comment by bhandari-aditya** [comment]
> Figured it out. Didn't look in the docs that adding the listeners is compulsory for these to work.

can you please explain here.. how you did that.
