### ISSUE TITLE
Add card in lane

### ISSUE THREAD

**Issue by lourenci** [lourenci/react-kanban#18]
It would be nice if we could add a new card in the lane. It would be nicer if we could allow to choose between add in the top of the lane or in the bottom of it.

**Comment by mkamranhamid** [comment]
I would like to take this issue but I would like little more explanation of this issue before taking it

**Comment by lourenci** [comment]
I'm not sure about the layout yet. But, I think we could use a "adder" like that one used to add a lane.

We could use a card adder placeholder either on the top of the lane or on the bottom of it depending of some prop like `addCardOn='top|bottom'`. On click, the "adder' would ask for a title or a description.

Do you have any ideia?

**Comment by lourenci** [comment]
Hi, @mkamranhamid. I've merged a PR #135 that will help on this issue.

**Comment by mkamranhamid** [comment]
![image](https://user-images.githubusercontent.com/11710104/65815573-9c385a80-e20a-11e9-9018-368a24617224.png)
The add button will be permanent or user can use it using prop `renderLaneHeader`. I was able to achieve this with prop `addCardOn='top|bottom'` and `renderLaneHeader`.

**Comment by lourenci** [comment]
This PR solves the need to add a card without using the `renderLaneHeader`.

I think we can do what we do with the lane adding feature:
* The user needs to pass an `allowAddCard`.
* If the user want, it can pass a prop to control where on the lane the card will be added (default to bottom) through `addCardOn='top|bottom`. 

As for the layout, what do you think about to create [something like the add lane feature](https://codesandbox.io/s/react-kanban-demo-hjskf?fontsize=14&view=preview)?

**Comment by mkamranhamid** [comment]
So basically this is what I'm going to do
* show an add sign/symbol next to `x` if a user passes a prop `allowAddCard`. 
* on pressing add sign will show a form (just like now we show a form for lane addition).
* on pressing confirm will call `onCardAdd` from the board

**Comment by lourenci** [comment]
I think you might have a problem with the new card id. You can use the same strategy used to add a new lane. I've plans to change this in the future.

**Comment by lourenci** [comment]
Don't forget to use the `addCardOn` prop. The `onCardAdd` accepts a third parameter to define the position of the new card.

Thanks.

**Comment by mkamranhamid** [comment]
![react-kanban-1](https://user-images.githubusercontent.com/11710104/65830463-28a95280-e2c9-11e9-81fd-001330841770.gif)

* For `id`, I used the `length` property of cards
* In `addCard` function we were looking for argument `on` so when passing arguments to `addCard` I put `addCardOn` value in `on` so that everything works as it's

This is my first open source contribution so apologies for asking so many dumb questions

**Comment by lourenci** [comment]
I think this is not the best strategy to generate the `id` for a new card:
* If you remove a card and add a new one, doing this again and again with other cards, a lot of cards will have the same id. I think it would break the react `key`.
* In the majority of the cases, the card will be saved to a backend. Probably, it's easier to the developer to get an `id` from the backend and keep track the card with this id.
Take a look at the the new lane feature, it suffers from the same problem. You could use the same strategy from there.

About the layout, I feel comfortable to add a "adder" in place of a read card. When the user clicks on this adder, the form will take place. [Think to the lane adder but for cards.](https://codesandbox.io/s/react-kanban-demo-hjskf?fontsize=14&view=preview)
This "plus" icon will conflict with the icon to remove a lane.

There is no dumb questions here. We are all here to help each other.

**Comment by mkamranhamid** [comment]
I looked at the lane feature and it's using a callback [function](https://github.com/lourenci/react-kanban#onlanenew) `onLaneNew` which returns the object with its `id` from a user and then this id is used later on.
should I do the same for cards? We have a `onCardNew` method for cards we can use that.
For the design, we can make a circle around `+` sign so that it's differentiable and not messed up with `x`

**Comment by lourenci** [comment]
I think you should do the same for the cards.

I cannot visualize the `+` working well here. We could try it if you want.

**Comment by mkamranhamid** [comment]
![image](https://user-images.githubusercontent.com/11710104/65895335-be75d800-e3c4-11e9-8ca4-c1190a4b6d18.png)
We can do it something like this if it looks good or a button with text "adder"?

**Comment by lourenci** [comment]
Could you please send me a screenshot with the `allowRemoveLane`?

**Comment by mkamranhamid** [comment]
![image](https://user-images.githubusercontent.com/11710104/65898572-4a8afe00-e3cb-11e9-8537-5d679816a547.png)
Sorry for taking long I was not able to import the styled component turns out it was a typo

**Comment by lourenci** [comment]
What do you think about a button like this:

![image](https://user-images.githubusercontent.com/2339362/65923598-df87fa00-e3bf-11e9-985e-9004b72445f2.png)

**Comment by mkamranhamid** [comment]
Can you make another issue for the redesigning of lane and it's actions I'll take it

**Comment by mkamranhamid** [comment]
![image](https://user-images.githubusercontent.com/11710104/66071958-8cec4080-e56d-11e9-8c18-da05bae8073f.png)
I'm getting this error when running command `npm test`. Can anyone help me out?

**Comment by lourenci** [comment]
Hi, @mkamranhamid. Sorry for the delay. Do you need some help here yet?

**Comment by mkamranhamid** [comment]
Yes I got busy at work and wasn't able to work on it If it's possible can you please take a look [here](https://github.com/mkamranhamid/react-kanban)

**Comment by lourenci** [comment]
Hi, @mkamranhamid. You changed the `addCard` to rely on the return of `onCardNew` callback. In the specs, your `onCardNew` (line 675) is returning nothing. Check the specs for the `addLane` callback (line 302), it's the same strategy.

I really recommend you to merge your branch with the master, there are a lot of changes there. You might have some conflicts.

**Comment by mkamranhamid** [comment]
Synced my fork and found that things have been changed a lot. Resolving the conflicts and will let you know if I get any blocker

**Comment by mkamranhamid** [comment]
merged the repo but there are few test errors

**Comment by lourenci** [comment]
Hi, @mkamranhamid. Let me know if you need some help here. We need to check this off to release the 1.0.0 version.

**Comment by mkamranhamid** [comment]
I'm not able to pass `tests`. I've pushed the code if anyone wants to start from there

**Comment by lourenci** [comment]
It was solved by #209.
