### ISSUE TITLE
Lane Styling

### ISSUE THREAD

**Issue by FryDerm** [lourenci/react-kanban#184]
Is there a way to make the lanes all be as tall as the one with the most cards in it?

**Comment by lourenci** [comment]
Hi, @FryDerm.

For the time being, we don't have any prop to configure this. We have some issues on the roadmap to allow a better way to configure styles for the board.

For now, what you can do is override the board styles. Can you try to put a `height` on the lane's parent?

**Comment by bofeiw** [comment]
A workaround is to add css to it. 

My way to add css is to find the class names it uses and style it in a separate .css file

https://github.com/lourenci/react-kanban/issues/141#issuecomment-552881770

**Comment by FryDerm** [comment]
The CSS class names appear to be mostly gibberish.  Will they stay the same all the time, or are they randomly generated?

**Comment by bofeiw** [comment]
> The CSS class names appear to be mostly gibberish. Will they stay the same all the time, or are they randomly generated?

From my experience of using it over the past month, the gibberish class names did not change over time nor on different environments

**Comment by lourenci** [comment]
@FryDerm from the time being, you can use this workaround. But, we have plans to support this in a proper way soon.

**Comment by lourenci** [comment]
We'll keep track of this in #141.

**Comment by FryDerm** [comment]
I've noticed other people's "random" class names match mine, so I'll go with it for now.  As far as having all lanes be 100% height, the following works for me:

`.sc-VigVT {
    min-height: 100%;
}

.sc-jTzLTM {
    height: 100%;
    display: inline-table;
}

.sc-htpNat {
    height: 100%;
    width: 380px;    
}

.sc-bxivhb {
    height: 100%;
}`
