### ISSUE TITLE
Card Drag: Uncaught TypeError: Cannot read property 'cards' of undefined

### ISSUE THREAD

**Issue by cstroked** [lourenci/react-kanban#229]
Hi,

I'm running into an issue where I'm getting the following:
`Uncaught TypeError: Cannot read property 'cards' of undefined`
Here's my board
```
<Board
        renderLaneHeader={lane => (
          <h4>
            {lane.title}
            <Button type="button" onClick={() => handleLaneRemove(lane)}>
              Remove Lane
            </Button>
          </h4>
        )}
        onLaneDragEnd={handleLaneDrag}
        onCardDragEnd={handleCardDrag}
      >
        {board}
      </Board>
```

And my drag handler:
```
  const handleCardDrag = (card, source, dest) => {
    // console.log(card, source, dest);
    const newBoard = moveCard(board, source, dest);
    setBoard(newBoard);
  };
```
It seems to be related to line 23 in `src/components/Board/services/index.js`
```
function getCard(board, sourceCoordinate) {
  const lane = board.lanes.find(lane => lane.id === sourceCoordinate.fromLaneId)
  return lane.cards[sourceCoordinate.fromPosition]
}
```
The compiled code:
```
function $a(e, n) {
      return e.lanes.find(function (e) {
        return e.id === n.fromLaneId;
      }).cards[n.fromPosition]; // this line causes the error
    }
```

Has anyone run into this or what I am missing? I currently can't even get it a `console.log` to log the function arguments... seems to break no matter what.

Thanks!

**Comment by lourenci** [comment]
Hi, @cstroked. Could you please reproduce your problem in a codesandbox? You can use this template: https://codesandbox.io/s/5k7py44kl.

I'm interested in the shape of your `board`.

**Comment by cstroked** [comment]
Hey @lourenci thanks for getting back to me. Sorry I forgot to mention this, you've created a tremendous library! 

Here's my demo: https://codesandbox.io/s/react-kanban-demo-b5r6t

Please let me know what I've screwed up here. I can't seem to figure it out! 

Thank you.

**Comment by cstroked** [comment]
This seems to be related to using a non-integer (in my case, using a uuid) as the id for a lane.

**Comment by shd101wyy** [comment]
Yeah I encountered the same issue. I am also using uuid as id instead of integer.

**Comment by lourenci** [comment]
Thanks for the report. There is a new version published with this correction.
