### ISSUE TITLE
Is it possible to provide APIs to customize the style of the board?

### ISSUE THREAD

**Issue by shd101wyy** [lourenci/react-kanban#230]
Hi there,

First of all, thank you very much for your awesome work!  
Is it possible to provide APIs so that we can customize the style of the board, just like how [rcdexta/react-trello did](https://github.com/rcdexta/react-trello#styling-and-customization here).
I basically want to change the background color of the lanes.

Thank you!

**Comment by shd101wyy** [comment]
Also would be awesome if we can modify the lane footer component.

**Comment by lourenci** [comment]
Hi, @shd101wyy.

We don't provide an API to change the board's styles straightforward, though you can do that overriding the generated styles through CSS (maybe you need some `!important`).

However, we have an issue already tracking this (#141) and as soon as possible that issue will be resolved. I'll put that on the v1 roadmap.

Thanks for the report.
