### ISSUE TITLE
Remove styled-components in favor of "native" solutions

### ISSUE THREAD

**Issue by lourenci** [lourenci/react-kanban#237]
`styled-components` was good for having fun (one of the project's purpose), but it goes against another project's purpose that is being pluggable. When using this lib with another lib on a project that that is using `styled-components` too, it could conflict, since the `styled-components` ask for being a peer dependency and the other lib could be asking for a different version of the `styled-component`.

So, I'm proposing to change the board to using "native" solutions like `css` or `css-in-js` (without the styled-components).

**Comment by tiagostutz** [comment]
Is this issue still opened? I noticed that it was supposed to be closed at the PR #278 merge but the merge has happened and the issue is still opened.

Does this issue needs any help?

**Comment by lourenci** [comment]
Hi, @tiagostutz.

The reason for this issue being opened is because the PR was only merged into the `beta` branch. This issue is going to be closed as soon as the beta gets merged into the `master` branch.

I'm planning to merge this as soon as I get enough feedback about the CSS API exposed there.

You can try it through the beta release (`yarn add @lourenci/react-kanban@beta`). [Here the docs for the CSS API](https://github.com/lourenci/react-kanban/tree/beta#-styling).
