### ISSUE TITLE
Allow the component be controlled?

### ISSUE THREAD

**Issue by lourenci** [lourenci/react-kanban#24]

**Comment by GLuchtenberg** [comment]
more info please

**Comment by lourenci** [comment]
Hi, @GLuchtenberg. It's about the board being either [controlled and or not controlled](https://reactjs.org/docs/forms.html#controlled-components). 

I prefer to handle this myself. I'm a heavy user of this board in a private project and I know some "pains" and how to handle them. Sorry for that.

**Comment by bofeiw** [comment]
I think it is better to provide some *optinal* APIs like `getBoard` and `setBoard` bcos it is useful to have.
