### ISSUE TITLE
How to override Column style

### ISSUE THREAD

**Issue by nalex88** [lourenci/react-kanban#273]
Hi i'am Alessandro,
first thanks for your great job with react-kanban.

i need to override the column style, there is the way for this?
How i can use styled-components or vanilla css via className?

thanks for your reply

Ale

**Comment by lourenci** [comment]
Hi, @nalex88. Thanks to reach out to us.

We don't have a straightforward way to do that yet. We're working on #141 to provide that.
For the time being, you can override the [gibberish ones generated by the lib](https://github.com/lourenci/react-kanban/issues/141#issuecomment-552881770).
