### ISSUE TITLE
Dragging a card to any part of the column

### ISSUE THREAD

**Issue by dimakrsna** [lourenci/react-kanban#300]
Hi, thanks for the nice plugin!
I had a problem with dragging a card to any part of the column, can this be fixed somehow?
![issue](https://user-images.githubusercontent.com/19911335/77317173-5e2c7700-6d13-11ea-8a42-c822241181dd.gif)

**Comment by lourenci** [comment]
Hi, @dimakrsna.

I’m out for now, but have you tried to increase the column's height?

**Comment by dimakrsna** [comment]
Column increase did not help :(

**Comment by Sabrinovsky** [comment]
@dimakrsna i found out why the column sizing was not working. I created a PR #338 that fix that.

If you dont want till it is merged, you can change the css of the div that are wrapping the cards.
This codesanbox has the workaround https://codesandbox.io/s/react-kanban-demo-9x93d?file=/src/index.js if you want to check it out :)

let me know if you have any question, hope you enjoy the lib

**Comment by dimakrsna** [comment]
@Sabrinovsky Thanks for the response to the issue.

**Comment by Sabrinovsky** [comment]
@dimakrsna in the codesanbox i manually wrote the code we just merged in the master, so you could copy it. The fixed version should be deployed soon.

By the way, you styled the board very nice xD
I'll try to write some css just like you did for our demo
