### ISSUE TITLE
Add new column in uncontrolled board

### ISSUE THREAD

**Issue by s-mahdi** [lourenci/react-kanban#305]
Hey. I am trying to use the default button to add a new column on the **uncontrolled** board. as mentioned in the [documentation](https://github.com/lourenci/react-kanban#onnewcolumnconfirm) I used `onNewColumnConfirm` prop to do so. I'm trying to do this like this: 
```typescript
onNewColumnConfirm={(draftColumn: any) => {
          return {
            id: new Date().getTime(),
            ...draftColumn
          };
        }}
```
but it doesn't add any column. am I did something wrong?
also I'm using **typescript**.
**dependencies**:
"react": "^16.13.1"
"styled-components": "^5.0.1"
"@lourenci/react-kanban": "^1.1.0"

**Comment by lourenci** [comment]
Hi, @smmh1376. 

Could you please make a codesandox example with your code?

Thanks.

**Comment by iIdiomatic** [comment]
@s-mahdi  Hope you using "allowAddColumn" property as well. Code is working for me.

**Comment by wuichen** [comment]
im seeing the same issue. this is my code ```const board = {
  columns: [
    {
      id: 1,
      title: 'Backlog',
      cards: [
        {
          id: 1,
          title: 'Add card',
          description: 'Add capability to add a card in a column',
        },
      ],
    },
    {
      id: 2,
      title: 'Doing',
      cards: [
        {
          id: 2,
          title: 'Drag-n-drop support',
          description: 'Move a card between the columns',
        },
      ],
    },
  ],
};
const Planner = () => {
  return (
    <>
      <h1>Page Planner</h1>
      <Board
        allowAddCard
        allowAddColumn
        onNewColumnConfirm={(added) => {
          console.log(added);
          const newColumn = { id: 13, cards: [], ...added };
          return newColumn;
        }}
        initialBoard={board}
      />
    </>
  );
};

export default Planner;```

**Comment by lourenci** [comment]
Hi, @wuichen.

To allow the user to add a new column in an uncontrolled board, you have to set 3 props:
```
<Board allowAddColumn onNewColumnConfirm={noop} onColumnNew={noop} />
```

Sorry if the documentation does not allow you to understand that, we have an issue to tidy it up.
