### ISSUE TITLE
Filtering on card props

### ISSUE THREAD

**Issue by MilesHart** [lourenci/react-kanban#327]
What is the prefered way to filter on card properties?

I can map over the columns and then filter on card props, however filter will return an array of columns and not a native array of json objects.

Any best ways to approach this?

**Comment by Sabrinovsky** [comment]
I don't know if I understood your problem correctly :/

Can you share some example?

**Comment by MilesHart** [comment]
hey thanks, I think I managed it, I used a straight up filter, in the end and had to map through the columns. 

Thank you
