### ISSUE TITLE
Unable to import the react-kanban components

### ISSUE THREAD

**Issue by KyleRAnderson** [lourenci/react-kanban#361]
I've got a Rails backend React frontend application going, and I needed a Kanban-like board for one of my views. I've got the setup using webpack and additionally am using Typescript to write my frontend code.

I'm trying to get started with this library. I've added `styled-components` as well as the `react-kanban` libraries to my project via `yarn add styled-components @lourenci/react-kanban`. They resolved to versions `5.1.1` and `1.1.1` respectively.

I'm now trying to use them in my application, however the line `import Board, { moveCard } from '@lourenci/react-kanban';` generates the following error:
```
ERROR in ./app/javascript/components/auth_pages/app_pages/matches/MatchmakeForm.tsx 32:28-33
"export 'default' (imported as 'Board') was not found in '@lourenci/react-kanban'
```

I'm really not sure what's going on here, I've used other libraries in my frontend (such as the `react-notifications-component` library) before with no issues.

Any help would be appreciated.

**Comment by Sabrinovsky** [comment]
Hi, i could not replicate this error in a tsx project. Have you check your tsconfig? 
Maybe can you reproduce it on codesandbox?

**Comment by KyleRAnderson** [comment]
Hello. Unfortunately, I'm not able to reproduce the error in a CodeSandbox. I'm really not sure what could be wrong here, other javascript libraries work nicely.

I'll share my TSConfig and the setup steps that I performed in case that's helpful.

`tsconfig.json`
```json
{
    "compilerOptions": {
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": ["es6", "dom"],
        "module": "es6",
        "moduleResolution": "node",
        "sourceMap": true,
        "target": "ES6",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "allowJs": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "noUnusedParameters": true,
        "noUnusedLocals": true
    },
    "exclude": ["**/*.spec.ts", "node_modules", "vendor", "public"],
    "include": ["app", "javascript", "decs.d.ts"],
    "compileOnSave": false
}
```
My typescript declaration file, which I use to tell typescript to ignore that there are no typings in the library:
`decs.d.ts`
```typescript
declare module 'react-notifications-component'; // Another library that I'm using that works with this setup.
declare module '@lourenci/react-kanban';
```

_The component in which I'm trying to use the Board_
```tsx
import React, { useState } from 'react';
import Board, { moveCard } from '@lourenci/react-kanban';
import MatchAPI from '../../../../api/matchAPI';
import { Button } from 'react-bootstrap';

type Props = {
    onSubmit?: (matchmakeParams: MatchAPI.MatchmakeParams) => void;
    participantProperties: string[];
};

type Card = {
    id: number | string;
    title: string;
    description?: string;
};

type DndColumn = {
    id: number | string;
    title: string;
    cards: Card[];
};

type Board = DndColumn[];

export default function MatchmakeForm(props: Props): JSX.Element {
    const propertiesCards: Card[] = props.participantProperties.map((property, index) => {
        return { id: index, title: property };
    });
    const initialBoard: Board = [
        { id: 1, title: 'Properties', cards: propertiesCards },
        { id: 2, title: 'Within', cards: [] },
        { id: 3, title: 'Between', cards: [] },
    ];

    const [board, setBoard] = useState<Board>(initialBoard);

    function onFormSubmit(): void {
        props.onSubmit?.(grabProperties());
        resetForm();
    }

    function resetForm(): void {
        setBoard(initialBoard);
    }

    function grabProperties(): MatchAPI.MatchmakeParams {
        const withinProperties: string[] = board[1].cards.map((card) => card.title);
        const betweenProperties: string[] = board[2].cards.map((card) => card.title);
        return { within: withinProperties, between: betweenProperties };
    }

    function handleCardMove(_card: any, source: any, destination: any) {
        const updatedBoard: Board = moveCard(board, source, destination);
        setBoard(updatedBoard);
    }

    return (
        <>
            <Board onCardDragEnd={handleCardMove} disableColumnDrag>
                {board}
            </Board>
            <Button onClick={() => onFormSubmit()}>Matchmake!</Button>
        </>
    );
}
```

# Setup Steps
1. `yarn add @lourenci/react-kanban styled-components`
1. Added the library to the typescript declarations file `decs.d.ts`, which is in my `tsconfig`. 
1. Made the component and tried compiling.

**Comment by Sabrinovsky** [comment]
@KyleRAnderson, i did just liek you said and worked fine for me. 
I noticed a little mistake on the Board type i think it should me something like:

`type Board = {
    columns: DndColumn[]
};
`
I did not tested any of the functions or the services you have, but the project builded correctly

Just to you know, i'm working on migrate the lib to typescript. I'm studying it yet, so i cant promisse anything in a short time :/

**Comment by johnykov** [comment]
I'm facing the same issue with this lib and webpacker for rails project, @KyleRAnderson did you solve that issue?

**Comment by KyleRAnderson** [comment]
> I'm facing the same issue with this lib and webpacker for rails project, @KyleRAnderson did you solve that issue?

Unfortunately not, I worked around it in other ways.
