### ISSUE TITLE
onClick

### ISSUE THREAD

**Issue by neowenshun** [lourenci/react-kanban#372]
i wish to use this kanban board as a list page , is there an api to handle onClick events?

**Comment by lourenci** [comment]
Hi, @neowenshun.

We don't expose `onClick` events out-of-the-box. You're able to achieve that by using the `renderCard` and `renderColumnHeader` props, though you'll have to render your own templates for that.

**Comment by lourenci** [comment]
I'll close this issue for now, we don't have plans to support that sooner.

Feel free to reaching out to us again.

Thank you.
