### ISSUE TITLE
Issue on renderColumnHeader - Cannot read property 'renameColumn' of undefined

### ISSUE THREAD

**Issue by MoiseScalzo** [lourenci/react-kanban#399]
Hi,
I encountered this error while working on renderColumnHeader and following the documentation:

**Cannot read property 'renameColumn' of undefined:**

Here a sandbox:
https://codesandbox.io/s/react-kanban-demo-forked-m5097?fontsize=14&hidenavigation=1&theme=dark

**Comment by Sabrinovsky** [comment]
Hi @MoiseScalzo thanks for the feedback

When the board is controlled the columnBag is not passed to the RenderColumnHeader. 

We gotta update the docs

**Comment by MoiseScalzo** [comment]
Hi @Sabrinovsky,
thanks for the answer...
