### ISSUE TITLE
Full copy?

### ISSUE THREAD

**Issue by guilopes22** [lourenci/react-kanban#92]
lol

even the readme have you copied from @lucasbesen repo?

https://github.com/lucasbesen/react-kanban-dnd

**Comment by lourenci** [comment]
Honestly, I don't remember. I tried to use a lot of kanban like libs, but they're very limited for my purpose.

I really don't understand the problem here. Isn't that repo under MIT licence?

Feel free to use any of them, anyway you want.

**Comment by lourenci** [comment]
Sorry, I haven't catch that you are talking about the entire repo. I was thinking about the README.

Even I could copy and do "whatever" I want (MIT) with that repo, there is no copy here, the code is mine all the way. :)
One of the purpose with this repo is to having fun. Copy is not fun.
